---
title: School of Markets
author: Arvind Venkat
email: schoolofmarkets@gmail.com
description: The School of Markets presents the best learning opportunity for Students.
  Now, make that little pocket money on your own!
baseurl: "/schoolofmarkets.github.io"
url: arvindvenkat.github.io/schoolofmarkets.github.io
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
